# Base image
FROM postman/newman:5.3.1-alpine
# Add multiple mirrors
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.15/main" > /etc/apk/repositories && \
    echo "http://dl-2.alpinelinux.org/alpine/v3.15/main" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.15/community" >> /etc/apk/repositories && \
    echo "http://dl-2.alpinelinux.org/alpine/v3.15/community" >> /etc/apk/repositories

# Update and upgrade packages
RUN apk update && apk upgrade

# Install extra packages
RUN apk add --no-cache curl zip iputils


# Globally install the newman-reporter-csvallinone npm package
RUN npm install -g newman-reporter-csvallinone

# Set the DNS explicitly
RUN echo "nameserver 8.8.8.8" > /etc/custom_resolv.conf && \
    echo "nameserver 1.1.1.1" >> /etc/custom_resolv.conf

# Copy custom resolv.conf at runtime and set the entry point
ENTRYPOINT ["/bin/sh", "-c", "cp /etc/custom_resolv.conf /etc/resolv.conf && exec newman"]
# Remove the installation cache
RUN rm -rf /var/cache/apk/*

# Set environment variable
ENV NODE_PATH=/usr/local/lib/node_modules
# Set working directory
WORKDIR /etc/newman
# Keep the container running
CMD ["tail", "-f", "/dev/null"]